### PR TITLE
changed commands.json

### PR DESCRIPTION
**Pull request by kkarthikvk**
Added the value to json file to make more sense

### CODE REVIEW

**Comment by kkarthikvk** [comment]
Added value to json attempt 2

**Comment by mentor-tara** [comment]
Looks like something is wrong :astonished:	Please see the CI checks below for more information. Click the "Details" link for more information as shown in this screenshot.

Screenshot of CI checks[](error)

**Comment by kkarthikvk** [comment]
Check whether attempt3 works

**Comment by kkarthikvk** [comment]
All check passed

**Pull request closed without merging**
